version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels: ["dependencies", "ci"]
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels: ["dependencies", "python"]
    groups:
      python-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/k8s"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "docker"
    directory: "/scripts"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "docker"
    directory: "/k8s/homelab-siem-chart"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["dependencies", "helm"]

  - package-ecosystem: "gomod"
    directory: "/agent"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["dependencies", "go"]
