prometheus:
  prometheusSpec:
    retention: 3d
    resources:
      requests:
        cpu: 150m
        memory: 384Mi
      limits:
        cpu: 400m
        memory: 768Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

grafana:
  resources:
    requests:
      cpu: 80m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: true
    storageClassName: local-path
    size: 1Gi
  adminPassword: "changeme-siem-2026"
  service:
    type: NodePort
    nodePort: 30300

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 256Mi

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
