apiVersion: v1
kind: ConfigMap
metadata:
  name: siem-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "homelab-siem.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "syslog_enabled": {{ .Values.siem.config.syslogEnabled }},
      "syslog_port": {{ .Values.siem.config.syslogPort }},
      "watch_files": [],
      "web_port": {{ .Values.siem.config.port }}
    }
  FLASK_ENV: {{ .Values.siem.config.flaskEnv | quote }}
  SIEM_PORT: {{ .Values.siem.config.port | quote }}
  SIEM_DB_PATH: {{ .Values.siem.config.dbPath | quote }}
  PYTHONUNBUFFERED: "1"
  SIEM_DB_BACKEND: {{ ternary "postgres" .Values.siem.config.dbBackend .Values.postgres.enabled | quote }}
  {{- if .Values.postgres.enabled }}
  SIEM_POSTGRES_HOST: "postgres.{{ .Values.namespace.name }}.svc.cluster.local"
  SIEM_POSTGRES_PORT: "5432"
  SIEM_POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  SIEM_POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  {{- end }}
