{{- if .Values.siem.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector: {}
  policyTypes: ["Ingress", "Egress"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-siem-ingress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app: homelab-siem
  policyTypes: ["Ingress"]
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.siem.config.port }}
    - ports:
        - protocol: UDP
          port: {{ .Values.siem.config.syslogPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-siem-egress
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app: homelab-siem
  policyTypes: ["Egress"]
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 443
{{- end }}
