apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: homelab-siem
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-siem-ingress
  namespace: homelab-siem
spec:
  podSelector:
    matchLabels:
      app: homelab-siem
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 5000
    - ports:
        - protocol: UDP
          port: 5140
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-siem-egress
  namespace: homelab-siem
spec:
  podSelector:
    matchLabels:
      app: homelab-siem
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 443
