apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siem-db-pvc
  namespace: homelab-siem
  labels:
    app.kubernetes.io/name: homelab-siem
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
