FROM python:3.14-slim

WORKDIR /app

RUN pip install --no-cache-dir requests==2.32.3

COPY falco_collector.py .

RUN useradd -u 1000 -m collector
USER 1000

EXPOSE 2801

ENTRYPOINT ["python3", "falco_collector.py"]
CMD ["--mode", "webhook", "--port", "2801", "--siem", "http://siem-service.homelab-siem.svc.cluster.local"]
